django_blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from django.contrib.sitemaps import views as sitemap_views
from django.views.generic import TemplateView

from apps.blog.rss import LatestPostFeed
from apps.blog.sitemap import ArticleSitemap

from apps.blog.views import ArticleListView, ArticleDetailView, ArticleArchivesView
from apps.users.views import ProfileView
from apps.comment.views import AddCommentView

handler404 = 'apps.blog.views.page_not_found_view'
handler500 = 'apps.blog.views.server_error_view'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ArticleListView.as_view(), name='article-list'),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/<int:user_id>/', ProfileView.as_view(), name="profile"),
    path('article/<int:article_id>/', ArticleDetailView.as_view(), name='article-detail'),
    path('add_comment/<int:article_id>/', AddCommentView.as_view(), name='add-comment'),
    path('archives/', ArticleArchivesView.as_view(), name='article-archives'),
    path('rss/', LatestPostFeed(), name='rss'),
    path('sitemap.xml', sitemap_views.sitemap, {'sitemaps': {'articles': ArticleSitemap}}, name='sitemap'),
    path('mdeditor/', include('mdeditor.urls')),

    # 配置上传文件的访问url
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

apps/blog/models.py
import datetime

from django.contrib.auth.models import User
from django.core.cache import cache
from django.db import models
from django.conf import settings
from django.utils.functional import cached_property
from django.template.defaultfilters import truncatechars_html

import mistune
from mdeditor.fields import MDTextField


class Category(models.Model):
    """文章分类"""
    name = models.CharField(max_length=50, verbose_name="分类名称")
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name="父级分类")
    is_deleted = models.BooleanField(default=False, verbose_name="是否删除")
    is_nav = models.BooleanField(default=True, verbose_name="是否为主页导航")
    sort = models.PositiveIntegerField(verbose_name="排序编号")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name="创建者")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        unique_together = (("name", "parent_category"),)
        ordering = ['sort']

    def __str__(self):
        return self.name

    def clean(self):
        # 已删除的分类必然不放在主页导航
        if self.is_deleted and self.is_nav:
            self.is_nav = False

    def has_child(self):
        if self.category_set.all().count() > 0:
            return True
        else:
            return False

    @classmethod
    def get_category_tree(cls, obj=None):
        """
        将obj所有的子分类生成树形结构，如果不指定则生成Category里所有分类的树形结构
        返回结构示例：
        [
            {
                'current': obj,
                'subordinate': [],
            },
            {
                'current': obj,
                'subordinate': [
                    {
                        'current': obj,
                        'subordinate': [],
                    },
                    {
                        'current': obj,
                        'subordinate': [],
                    },
                ],
            },
            {
                'current': obj,
                'subordinate': [],
            }
        ]
        :param obj: Category实例，可以不指定，默认为None
        :return: list
        """
        tree = []
        objects = cls.objects.filter(parent_category=obj, is_nav=True)
        for obj in objects:
            if obj.has_child:
                subordinate = cls.get_category_tree(obj)
            else:
                subordinate = []
            tree.append({
                'current': obj,
                'subordinate': subordinate,
            })
        return tree


class Tag(models.Model):
    """文章标签"""
    name = models.CharField(max_length=50, unique=True, verbose_name="标签名称")
    is_deleted = models.BooleanField(default=False, verbose_name="是否删除")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name="创建者")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    @cached_property
    def article_count(self):
        return Article.objects.filter(tag__name=self.name, is_published=True).distinct().count()

    article_count.short_description = "文章数量"


class Article(models.Model):
    """文章"""
    title = models.CharField(max_length=255, verbose_name="标题")
    desc = models.CharField(max_length=1024, blank=True, null=True, verbose_name="摘要")
    content = MDTextField(verbose_name="正文")
    content_html = models.TextField(verbose_name="正文html代码", blank=True, editable=False)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, verbose_name="分类")
    tag = models.ManyToManyField(Tag, verbose_name="标签", blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name="作者")
    on_top = models.BooleanField(default=False, verbose_name="是否置顶")
    comment_allowed = models.BooleanField(default=True, verbose_name="是否允许评论")
    is_published = models.BooleanField(default=False, verbose_name="是否发布")
    pub_time = models.DateTimeField(null=True, verbose_name="发布时间")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    mod_time = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='articles_liked',
                                        blank=True, verbose_name="点赞用户")
    pv = models.PositiveIntegerField(default=0)
    uv = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ['-on_top', '-pub_time']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.content_html = mistune.markdown(self.content)
        super().save(*args, **kwargs)

    def clean(self):
        # 未发布的文章不应该有发布时间
        if not self.is_published and self.pub_time is not None:
            self.pub_time = None
        if self.is_published and self.pub_time is None:
            self.pub_time = datetime.datetime.now()
        # 置顶的文章必须是已发布的
        if self.on_top and not self.is_published:
            self.on_top = False

    def published(self):
        self.is_published = True
        self.pub_time = datetime.datetime.now()
        self.save(update_fields=['is_published', 'pub_time'])

    def next_article(self):
        # 下一篇文章
        return Article.objects.filter(
            pub_time__gt=self.pub_time, is_published=True).order_by('pub_time').first()

    def prev_article(self):
        # 前一篇文章
        return Article.objects.filter(
            pub_time__lt=self.pub_time, is_published=True).order_by('pub_time').last()

    @classmethod
    def latest_articles(cls, nums=None):
        if nums:
            return cls.objects.filter(is_published=True)[:nums]
        else:
            return cls.objects.filter(is_published=True)

    @classmethod
    def hottest_articles(cls, nums=None):
        if nums:
            return cls.objects.filter(is_published=True).order_by('-pv')[:nums]
        else:
            return cls.objects.filter(is_published=True).order_by('-pv')

    @cached_property
    def comment_num(self):
        return self.comment_set.filter(is_deleted=False).count()

    comment_num.short_description = "评论数量"

    @cached_property
    def tags(self):
        return ','.join(self.tag.values_list('name', flat=True))

    @cached_property
    def users_like_count(self):
        return self.users_like.all().count()

    users_like_count.short_description = "点赞数量"

apps/comment/models.py
from django.db import models
from django.conf import settings

from apps.blog.models import Article


class Comment(models.Model):
    """用户评论"""
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="文章")
    content = models.TextField(max_length=2000, verbose_name="评论内容")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name="作者")
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name="上级评论")
    is_deleted = models.BooleanField(default=False, verbose_name="是否删除")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    mod_time = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content

    def has_child(self):
        if self.comment_set.all().count() > 0:
            return True
        else:
            return False

    @classmethod
    def latest_comments(cls, nums=None):
        if nums:
            return cls.objects.filter(is_deleted=False).order_by('-created_time')[:nums]
        else:
            return cls.objects.filter(is_deleted=False).order_by('-created_time')

    @classmethod
    def get_comment_tree(cls, article, comment=None):
        """
        将指定Article实例的某个Comment实例的子评论生成树形结构，
        如果不指定Comment实例，则生成Article实例所有评论的树形结构
        返回结构示例：
        [
            {
                'current': obj,
                'subordinate': [],
            },
            {
                'current': obj,
                'subordinate': [
                    {
                        'current': obj,
                        'subordinate': [],
                    },
                    {
                        'current': obj,
                        'subordinate': [],
                    },
                ],
            },
            {
                'current': obj,
                'subordinate': [],
            }
        ]
        :param article: Article实例
        :param comment: Comment实例，可以不指定，默认为None
        :return: list
        """
        tree = []
        objects = cls.objects.filter(article=article, parent_comment=comment, is_deleted=False)
        for obj in objects:
            if obj.has_child:
                subordinate = cls.get_comment_tree(article, obj)
            else:
                subordinate = []
            tree.append({
                'current': obj,
                'subordinate': subordinate,
            })
        return tree

apps/blog/views.py
import pprint
import logging
from datetime import date

from django.core.cache import cache
from django.db.models import Q, F
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import render, get_object_or_404

from apps.config.models import SideBar, BlogSettings
from apps.comment.models import Comment
from .models import Article, Category, Tag
from .filters import ArticleFilter
from apps.comment.forms import CommentForm

from utils.blog_setting import get_blog_setting


class CommonViewMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'sidebars': self.get_sidebars(),
            'filter_form': ArticleFilter(self.request.GET, queryset=Article.objects.filter(is_published=True)).form,
            'category_tree': Category.get_category_tree(),
            'blog_setting': get_blog_setting(),
        })
        return context

    def get_sidebars(self):
        return SideBar.objects.filter(is_enable=True)


class ArticleListView(CommonViewMixin, ListView):
    paginate_by = get_blog_setting()['per_page_count']
    context_object_name = 'article_list'
    template_name = 'blog/list.html'

    def get_queryset(self):
        filter_queryset = ArticleFilter(self.request.GET, queryset=Article.latest_articles()).qs
        return filter_queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        filter_form = ArticleFilter(self.request.GET, queryset=Article.latest_articles()).form
        filter_items = {}

        if filter_form.is_valid():
            for k, v in filter_form.cleaned_data.items():
                if v:
                    filter_items[filter_form.fields[k].label] = v

        context.update({
            'filter_items': filter_items,
        })
        return context


class ArticleDetailView(CommonViewMixin, DetailView):
    queryset = Article.objects.filter(is_published=True)
    template_name = 'blog/detail.html'
    context_object_name = 'article'
    pk_url_kwarg = 'article_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'comment_tree': Comment.get_comment_tree(self.object),
            'comment_form': CommentForm(),
        })
        return context

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.handle_visited()
        return response

    def handle_visited(self):
        increase_pv = False
        increase_uv = False
        uid = self.request.uid
        pv_key = 'pv:%s:%s' % (uid, self.request.path)
        if not cache.get(pv_key):
            increase_pv = True
            cache.set(pv_key, 1, 1*60)  # 1分钟有效

        uv_key = 'uv:%s:%s:%s' % (uid, str(date.today()), self.request.path)
        if not cache.get(uv_key):
            increase_uv = True
            cache.set(uv_key, 1, 24*60*60)  # 24小时有效

        if increase_pv and increase_uv:
            Article.objects.filter(pk=self.object.id).update(pv=F('pv') + 1, uv=F('uv') + 1)
        elif increase_pv:
            Article.objects.filter(pk=self.object.id).update(pv=F('pv') + 1)
        elif increase_uv:
            Article.objects.filter(pk=self.object.id).update(uv=F('uv') + 1)


class ArticleArchivesView(CommonViewMixin, ListView):
    queryset = Article.objects.filter(is_published=True).order_by('-pub_time')
    context_object_name = 'article_list'
    template_name = 'blog/archives.html'


def page_not_found_view(request, exception):
    return render(request, '404.html', context={}, status=404)


def server_error_view(request):
    return render(request, '50x.html', context={}, status=500)

templates/blog/archives.html
{% extends "./base.html" %}
{% load static %}

{% block main %}

  <div class="py-3">
    <h3><strong>文章归档</strong></h3>
{#    <p><strong>文章归档</strong></p>#}
  </div>

  {% if article_list %}
    {% for article in article_list %}
      <div class="row no-gutters">

        {% if not article.pub_time.year == article.next_article.pub_time.year %}
          <div class="col-2 archives pt-2">
            <h3>{{ article.pub_time.year }}年</h3>
          </div>
        {% else %}
          <div class="col-2 pt-2">
          </div>
        {% endif %}

        {% if not article.pub_time|date:"Y-m" == article.next_article.pub_time|date:"Y-m" %}
          <div class="col-1 archives pt-2">
            <h4>{{ article.pub_time.month }}月</h4>
          </div>
        {% else %}
          <div class="col-1 pt-2">
          </div>
        {% endif %}

        <div class="col-1 archives py-2">
          <h5>{{ article.pub_time.day }}日</h5>
        </div>
        <div class="col-8 archives py-2">
          <h5>
            <a class="text-dark" href="{% url 'article-detail' article.id %}">
              {{ article.title }}
            </a>
          </h5>
          <p class="my-0 text-secondary">
            <small>
              分类：
              <a class="text-secondary" href="{% url 'article-list' %}?category={{ article.category.id }}">
                <u>{{ article.category }}</u></a>
              &emsp;&emsp;标签：
              {% for tag in article.tag.all %}
                <a class="text-secondary" href="{% url 'article-list' %}?tag={{ tag.id }}"><u>{{ tag }}</u></a>&ensp;
              {% endfor %}
            </small>
          </p>
        </div>

      </div><!-- /.blog-post -->
    {% endfor %}
  {% else %}
    <div class="p-3">
      <p>没有文章</p>
    </div>
  {% endif %}

{% endblock %}

templates/blog/base.html
{% load static %}
{% load blog_tags %}

<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>{% block title %}{{ blog_setting.site_name }}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog/blog.css' %}" rel="stylesheet">

    {% block extra_head %}
    {% endblock %}

  </head>

  <body>
    <div class="container">

      <div class="card bg-light text-white" style="border:none;">
        {% if blog_setting.background_image %}
          <img class="card-img" src="{{ blog_setting.background_image }}" alt="Card image">
        {% else %}
          <img class="card-img" src="{% static 'img/background_image.jpg' %}" alt="Card image">
        {% endif %}
        <div class="card-img-overlay">
          <h1 class="card-title p-4 font-weight-bold">{{ blog_setting.site_name }}</h1>
          <h4 class="card-text pl-4 font-weight-light">{{ blog_setting.site_description }}</h4>
        </div>
      </div>

      <div class="my-4 border-top border-bottom">
        <nav class="navbar navbar-expand-lg navbar-light">
          <a class="navbar-brand" href="{% url 'article-list' %}">首页</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">
              {% for category in category_tree %}
                {% if category.subordinate %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {{ category.current }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'article-list' %}?category={{ category.current.id }}">
                        {{ category.current }}</a>
                      <div class="dropdown-divider"></div>
                      {% for child_category in category.subordinate %}
                        <a class="dropdown-item" href="{% url 'article-list' %}?category={{ child_category.current.id }}">
                          {{ child_category.current }}</a>
                      {% endfor %}
                    </div>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'article-list' %}?category={{ category.current.id }}">
                      {{ category.current }}</a>
                  </li>
                {% endif %}
              {% endfor %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'article-archives' %}"><u>文章归档</u></a>
              </li>
            </ul>

            <form class="form-inline my-2 my-lg-0" action="{% url 'article-list' %}" method="get">
              <div class="input-group input-group-sm">
                <input type="text" name="key" class="form-control" placeholder="输入关键词"
                       aria-label="Recipient's username" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button class="btn btn-outline-secondary" type="submit">&emsp;搜索&emsp;</button>
                  <button class="btn btn-outline-secondary" type="button" data-toggle="collapse"
                          data-target="#filterBox" aria-expanded="false"
                          aria-controls="filterBox">高级筛选</button>
                </div>
              </div>
            </form>

          </div>
        </nav>

        <div class="collapse px-3 mb-4" id="filterBox">
          <div class="card card-body">
            <form action="{% url 'article-list' %}" method="get">
              <div class="form-row">
                {% for form in filter_form %}
                  <div class="form-group col">
                    <label for="{{ form.id_for_label }}" class="col-form-label col-form-label-sm">
                      {{ form.label }}
                    </label>
                    {{ form }}
                  </div>
                {% endfor %}
                <div class="form-group align-self-end">
                  <button class="btn btn-sm btn-secondary" type="submit">&emsp;提交&emsp;</button>
                </div>
              </div>
            </form>
          </div>
        </div>

      </div>

      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8 blog-main">

            {% block main %}
            {% endblock %}

          </div><!-- /.blog-main -->

          <aside class="col-md-4 blog-sidebar">

            {% if request.user.is_authenticated %}
              <div class="d-flex p-3">
                <div class="pr-3">
                  <a href="{% url 'profile' request.user.id %}">
                    <img src="{{ request.user.image.url }}" class="card-img rounded-circle head-image" alt="User Image">
                  </a>
                </div>
                <div>
                  <p class="mb-1"><strong>{{ request.user }}</strong>，欢迎光临！</p>
                  <a href="{% url 'account_logout' %}"><p class="text-muted">注销登录</p></a>
                </div>
              </div>
            {% else %}
              <div class="text-right pr-2">
                <a href="{% url 'account_login' %}"><p class="text-muted"><u>用户登录</u></p></a>
              </div>
            {% endif %}

            {% for sidebar in sidebars %}
              <div class="border-top mb-3 p-3">
                <p><strong>{{ sidebar.title }}</strong></p>
                {{ sidebar.content_html|safe }}
              </div>
            {% endfor %}

          </aside><!-- /.blog-sidebar -->

        </div><!-- /.row -->

      </main><!-- /.container -->

      <footer class="blog-footer mt-5">
        <p class="mb-1">Copyright&copy; {{ blog_setting.site_name }}</p>
        <ul class="list-inline mb-1">
          <li class="list-inline-item">Powered by <a href="https://www.djangoproject.com/" class="text-muted"><u>Django</u></a></li>|
          <li class="list-inline-item"><a href="https://github.com/luochaorobert/django_blog" class="text-muted"><u>Github</u></a></li>|
          <li class="list-inline-item"><a href="{% url 'sitemap' %}" class="text-muted"><u>SiteMap</u></a></li>|
          <li class="list-inline-item"><a href="{% url 'rss' %}" class="text-muted"><u>RSS</u></a></li>
        </ul>
        <a href="http://www.beian.miit.gov.cn/">
          <p class="text-muted"><u>{{ blog_setting.record_number }}</u></p>
        </a>
      </footer>

    </div>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    {% block custom_js %}
    {% endblock %}

  </body>
</html>

templates/blog/detail.html
{% extends "./base.html" %}
{% load static %}
{% load blog_tags %}
{% load comment_block %}

{% block extra_head %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block main %}
  {% if article %}
    <h2>{{ article.title }}</h2>
    <div class="my-3">
      <span><a class="text-muted" href="{% url 'article-list' %}"><u>剑客营</u></a></span> >
      {% if article.category.parent_category %}
        <span><a class="text-muted" href="{% url 'article-list' %}?category={{ article.category.parent_category.id }}">
          <u>{{ article.category.parent_category }}</u></a></span> >
      {% endif %}
      <span><a class="text-muted" href="{% url 'article-list' %}?category={{ article.category.id }}">
        <u>{{ article.category }}</u></a></span> >
      <span>{{ article.title }}</span>
    </div>
    <div class="d-flex justify-content-between">
      <div>
        <span>标签&ensp;</span>
        {% for tag in article.tag.all %}
          <a class="p-1 text-muted" href="{% url 'article-list' %}?tag={{ tag.id }}"><u>{{ tag }}</u></a>
        {% endfor %}
      </div>
      <div>
        <span>{{ article.pub_time }} by <a class="text-muted" href="{% url 'article-list' %}">
          <u>{{ article.author }}</u></a></span>
      </div>
    </div>
    <hr>
    <p>
      {% autoescape off %}
        {{ article.content_html }}
      {% endautoescape %}
    </p>
    <div class="py-4 px-2 my-4 d-flex justify-content-between border-top border-bottom">
      <div>
        {% if article.next_article %}
          <a class="text-muted" href="{% url 'article-detail' article.next_article.id %}">
            <u><< {{ article.next_article.title }}</u></a>
        {% else %}
          已经是最新一篇
        {% endif %}
      </div>
      <div>
        {% if article.prev_article %}
          <a class="text-muted" href="{% url 'article-detail' article.prev_article.id %}">
            <u>{{ article.prev_article.title }} >></u></a>
        {% else %}
          已经是最早一篇
        {% endif %}
      </div>
    </div>

    <!-- 评论输入框 -->
    <form method="POST" action="{% url 'add-comment' article.id %}" id="commentForm">
      {% csrf_token %}
      <div class="card mb-3">
        {% if blog_setting.open_site_comment and article.comment_allowed and request.user.is_authenticated %}
          <div class="card-header d-flex">
            <strong>发表评论</strong>
            <div class="ml-3 text-black-50" id="commentObject">
              <small>
                回复：
                <strong><span id="replyCommentAuthor"></span></strong>&nbsp;
                <span id="replyCommentContent"></span>
              </small>&nbsp;
              <a href="javascript:void(0);" id="cancelReply"><small class="text-muted"><u>取消回复</u></small></a>
            </div>
          </div>
          <div class="card-body">
            <div class="form-group">
              {{ comment_form.as_table }}
            </div>
          </div>
          <div class="card-footer text-muted text-right">
            <button class="btn btn-sm btn-info" type="submit">发表评论</button>
          </div>
        {% elif not request.user.is_authenticated %}
          <div class="card-header d-flex">
            <strong>发表评论</strong>
          </div>
          <div class="card-body">
            您还没有登录，请登录后发表评论。
          </div>
          <div class="card-footer text-muted text-right">
            <a href="{% url 'account_login' %}?next=/article/{{ article.id }}/" type="button" class="btn btn-sm btn-info">用户登录</a>
          </div>
        {% else %}
          <div class="card-header d-flex">
            <strong>发表评论</strong>
          </div>
          <div class="card-body">
            当前禁止评论。
          </div>
        {% endif %}
      </div>
    </form>

    <!-- 评论数目 -->
    <div class="mt-4">
      <h5><strong>{{ article.comment_num }}</strong>&nbsp;评论</h5>
    </div>

    <!-- 目录列表 -->
    <ul class="list-group">
      {% comment_block comment_tree %}
    </ul>

  {% endif %}

{% endblock %}

{% block custom_js %}
  <script>

    $(document).ready(function(){
      $('#commentObject').hide();
    });

    // 处理点击回复按钮的事件
    function reply_comment(comment_id, comment_author, comment_content) {
      // 为评论表单的parent_comment字段添加value
      $('#id_parent_comment').val(comment_id);
      // 将回复对象和内容展示在评论表单头部
      $('#replyCommentAuthor').text(comment_author);
      $('#replyCommentContent').text(comment_content);
      $('#commentObject').show();
    }

    // 取消回复
    $('#cancelReply').on("click", function () {
      // 将评论表单的parent_comment字段重置为空
      $('#id_parent_comment').val(null);
      // 取消回复对象和内容展示在评论表单头部
      $('#commentObject').hide();
    })

  </script>
{% endblock %}